apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: multi-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
        app: multi-k8s
    spec:
      containers:
        - name: client
          image: agalue/poc-multi-client:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
